### ISSUE TITLE
Remove sidebar

### ISSUE THREAD

**Issue by luis100** [keeps/roda#1261]
Needs:
- [x] Add breadcrumbs to replace "back" buttons #1270
- [x] Re-implement actions in all entities using the Actionable interface #885
- [x] Implement actions layout as a contextual menu instead of sidebar #1259
- [x] Remove date filter from sidebar and add it as advanced search #1260
- [x] Card filters #1116
