### ISSUE TITLE
Identify missing format representation information plugin based on extra fields

### ISSUE THREAD

**Issue by luis100** [keeps/roda#721]
Allow to search representation information by:
- [ ] Search format designation also on alternative designations, see #719 
- [ ] Search format version on versions, see #719 
- [ ] Search file name extension on extensions, see #720

**Comment by rui-castro** [comment]
@luis100 @jmaferreira don't assign me more tasks for this sprint.

**Comment by rui-castro** [comment]
@luis100 what is the expected output of this task?

**Comment by rui-castro** [comment]
@luis100 ping

**Comment by luis100** [comment]
On the missing format representation information plugin, the plugin goes through files and tries to find representation information that fits the file information based on the file characterization information, as file format designation to be on the rep. info. format title, pronom to be on rep. info. format pronoms, etc.

Enhance this to also search:
* File format designation on rep. info. format alternative designations
* File format designation version on rep. info. format versions
* File name extension on rep. info. format file name extensions

**Comment by rui-castro** [comment]
Blocked by #740

**Comment by rui-castro** [comment]
@luis100 done in #742

**Comment by luis100** [comment]
The code was already merged.

But the following case was found: format has extension xml, several format records for XML exist, but yet none found. To note that other XML files passed.

Format record:
![xml_format](https://cloud.githubusercontent.com/assets/631728/21593975/3e07f4f6-d115-11e6-826a-ac6419e7df7c.png)


Report that failed:
![report_failure_filename](https://cloud.githubusercontent.com/assets/631728/21593985/54fc4d9c-d115-11e6-80f9-609ceb9e13d0.png)

Report that passed:
![report_passed](https://cloud.githubusercontent.com/assets/631728/21593988/5ddbcd98-d115-11e6-8a99-b441f72817e3.png)

**Comment by jmaferreira** [comment]
@rui-castro the plugin was run with the option "ANY"

**Comment by rui-castro** [comment]
@jmaferreira @luis100 I see... Let me check it again.

**Comment by rui-castro** [comment]
@jmaferreira @luis100 fixed in PR #763

**Comment by hsilva-keep** [comment]
PR #763 indeed solves the last issue raised (error when several formats matched). Closing this issue as the code has been merged.
